### ISSUE TITLE
新问题：rename表的问题

### ISSUE THREAD

**Issue by listen-zhou** [rolandhe/hiriver#4]
有些数据库会建一个临时表，然后将临时表rename成为正式表，然后再将临时表删除，这各操作是连贯执行的，档binlog解析程序解析到临时表的时候，发现表不存在，就会报错，这个应该怎么规避，遇到表不存在的情况，像见下图。

![image](https://user-images.githubusercontent.com/9762143/64218089-c68c4600-cef2-11e9-91c2-6e6e7ee9febd.png)
这个报错成了一个死循环，这个pos一直跳不过去，释放资源后，重新load断点后会是会加载这个pos，结果还是一样的报错，进行不下去，是不是不要释放资源，直接运行下去？

**Comment by listen-zhou** [comment]
![image](https://user-images.githubusercontent.com/9762143/64218427-26372100-cef4-11e9-8f73-56ed0868d132.png)

**Comment by listen-zhou** [comment]
![image](https://user-images.githubusercontent.com/9762143/64218506-84640400-cef4-11e9-97b2-c3a46012e16a.png)

遇到这样的问题，临时表rename为正式表的情况，我觉得可以跳过这个异常，本身临时表就是临时出现，不知道你有何高见。

**Comment by rolandhe** [comment]
设置黑名单，把这些临时表过滤掉。


------------------ 原始邮件 ------------------
发件人: 周梦强 <notifications@github.com&gt;
发送时间: 2019年9月4日 09:15
收件人: rolandhe/hiriver <hiriver@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[rolandhe/hiriver] 新问题：rename表的问题 (#4)

**Comment by rolandhe** [comment]
# 白名单，通过表名过滤，支持正则，表名必须是 库名.表名格式
table.white=rpl.*
# 黑名单，通过表明过滤，支持正则，表名必须是 库名.表名格式
table.black=

你可以设置黑名单来解决。

**Comment by listen-zhou** [comment]
ok，谢谢。
