### ISSUE TITLE
接着一个gbk乱码的

### ISSUE THREAD

**Issue by listen-zhou** [rolandhe/hiriver#5]
如果把配置的gbk编码bean去掉，还是有中文乱码，我测试的结果是这样的。

**Comment by rolandhe** [comment]
1. 是不是没有更新代码？配置的功能已经删除掉了，改用Show column 读取表元数据了。之前的代码在处理utf8mb4时会有问题，你用gbk应该没有问题。注：r1.2.4分支代码
2. 最新代码修复了utf8mb4问题，请用master最新代码。

**Comment by listen-zhou** [comment]
![image](https://user-images.githubusercontent.com/9762143/64667498-944b8d00-d48c-11e9-98ec-3aaeb003feb3.png)
已经是最新版本的代码了，如果不加那个gbk的配置，还是会乱码。

**Comment by listen-zhou** [comment]
可以了，不配置gbk，也不会乱码了，是我自己版本号没有配置好，这次你升级了版本号，我在simple里面的版本号没有改，导致还是老代码，谢谢。我刚才把你这次提交的变更都对比了一遍，才发现，java代码更新了，但是pom的版本号没有修改。
