### ISSUE TITLE
我发现一个bug，日期解析时会增大一个月，望修复

### ISSUE THREAD

**Issue by listen-zhou** [rolandhe/hiriver#8]
具体如下：
public class DateColumnTypeValueParser implements ColumnTypeValueParser {

    @Override
    public Object parse(byte[] buf, Position pos, ColumnDefinition columnDef, int meta) {
        int tmp = MysqlNumberUtils.read3Int(buf, pos);
        int day = tmp & 31;
        int month = (tmp >> 5 & 15);
        int year = tmp >> 9;
        Calendar cal = Calendar.getInstance();
        cal.set(year, month, day, 0, 0, 0);
        return cal.getTime();
    }

}

这个方法里面的cal.set在设置月份的时候是从0开始的，也就是0代表1月份，而实际从binlog解析出来的日期中的月份就是实际的月份数字，不是从0开始，所以这个地方的cal.set 参数month要减1才对。怎么发现的呢，是我发现同步到目标表中的数据日期总是大了一个月，然后我就反查代码，发现是这里出了问题。
不知道其他的地方解析，关于日期和数字的会不会有这样的问题。

**Comment by rolandhe** [comment]
更新了。

感谢提交这个问题。这是个已知问题，另一位同学已经修复了，忘记提交了，其他的没有这个问题。
